### ISSUE TITLE
Sick-Day-Tracker (SB) implementation

### ISSUE THREAD

**Issue by DannyDannyDanny** [alexdor/NV-HR-LAB#10]
If an employee has gone AWOL or is disproportionately sick, SB takes the days (the date and number of hours on the sick-days) and calculates whether or not the employer is entitled to fire the employee.

The tool assumes the employee has an average work day of 7.4 hours (37 hours per 5-day-work-week) but the daily work time can changed. 

![NV-export 1 2 021](https://user-images.githubusercontent.com/16453674/65173417-fee16780-da4e-11e9-8247-72407dd4a4ae.jpeg)

A sort-of table is built as the user fills in the date and sick-hours. The columns:
* **Fraværsdato** - the date, entered by user
* **Ugedag** - day of the week, some days are worth more than others
  * Example: full-day sick monday + full-day sick friday = 4 sick days
* **Timer** - number of hours sick (maximum one full average work day)
* **Dage** - decimal-fraction of the work day spent sick
* **Dage sygefravær** - cumulative days sick (as summed decimal)

The user fills a day at the time:

![NV-export 1 2 022](https://user-images.githubusercontent.com/16453674/65173398-f426d280-da4e-11e9-9a5b-9b04a6a8ac26.jpeg)

Once all sick days have been filled in, a PDF transcript can be downloaded via a "export as PDF"-type button.

![NV-export 1 2 023](https://user-images.githubusercontent.com/16453674/65173400-f6892c80-da4e-11e9-84a0-f993c86bf337.jpeg)

## [Prototype](https://taigacompany.github.io/c01-nvtoolbox/#/SygedagsBeregner) 
The current prototype sums days registered without extra rules. Try it [here](https://taigacompany.github.io/c01-nvtoolbox/#/SygedagsBeregner). Use Google Chrome when visiting from a desktop / laptop computer.

To continue development we need business logic and several examples from NV. We need to document rules (weekend rule, holiday rule and conditions for termination/firing (opsigelse).

## Calculation Logic
* **weekend rule** - If Friday **and** Monday were full sick days, count Saturday and Sunday as sick days too.
* **holiday rule** - Similarly, with holidays. if the day before **and** the day after the holiday(s) were full-sick days, count the holiday(s) as a sick day too.

## Functionailty [![QNV](https://img.shields.io/badge/Question-NorrbomVinding-orange)](#questions)
* Show how many hours / work-days remain until firing / termination in order.

## Actionable:
* [x] Find resource with Danish holidays: 
  * [Calendarific API](https://calendarific.com)
  * [Salling Group Holiday API](https://developer.sallinggroup.com/api-reference?fbclid=IwAR0hLrKYR25dZB7LwLHIjr9tqEbbLPod2xsD6zwhTDWFgPGGsWAQETyKMGU#apis-holidays) - uses JWT
* [x] Implement weekend rule
* [ ] Implement holidays rule
* [ ] Internal testing
